CREATE DATABASE SE;
GO
USE SE;
CREATE TABLE USER_ACCOUNT
(
	ID			INT	PRIMARY KEY IDENTITY(1,1),
	UserName	NVARCHAR(20)		NOT NULL UNIQUE,
	Password	NVARCHAR(20)		NOT NULL,
	FName		NVARCHAR(20)		NOT NULL,
	LName		NVARCHAR(20)		NOT NULL,
	BirthOfDate	NVARCHAR(10)		NOT NULL,
	Address		NVARCHAR(300)		NOT NULL,
	PhoneNumber	NVARCHAR(10)		NOT NULL,
	Img			NVARCHAR(20),
	TypeOfUser  NVARCHAR(20)		NOT NULL
);

CREATE TABLE FOOD
(
	FoodID		INT	PRIMARY KEY IDENTITY(1,1),
	Name		NVARCHAR(20)		NOT NULL,
	Description	NVARCHAR(200)		NOT NULL,
	Price		NVARCHAR(10)		NOT NULL,
	PathImg		NVARCHAR(100)	NOT NULL,
	Category	NVARCHAR(100)	NOT NULL,
	Available		INT				NOT NULL
)

CREATE TABLE PAYMENT
(
	CustomerID	INT	NOT NULL,
	OrderID		INT NOT NULL,
	Paytype		NVARCHAR(10) NOT NULL,
	Total		NVARCHAR(10) NOT NULL,
	Name		NVARCHAR(20) NOT NULL,
	Address		NVARCHAR(300) NOT NULL,
	PhoneNumber	NVARCHAR(10) NOT NULL,
	PRIMARY KEY	(CustomerID,OrderID),
	CONSTRAINT fk_cus_pay FOREIGN KEY (CustomerID)
				REFERENCES USER_ACCOUNT(ID)
				ON DELETE NO ACTION
)


CREATE TABLE ORDER_FOOD
(
	OrderID		INT	PRIMARY KEY IDENTITY(1,1),
	Date		NVARCHAR(100) NOT NULL,
	Status		NVARCHAR(20) NOT NULL,
	ClerkID		INT	NOT NULL,
	CONSTRAINT 	fk_pay_custom	FOREIGN KEY (ClerkID)
				REFERENCES USER_ACCOUNT(ID)
				ON DELETE NO ACTION
)

CREATE TABLE ORDERED
(
	CustomerID	INT	NOT NULL,
	OrderID		INT	NOT NULL,
	FoodID		INT	NOT NULL,
	Quantity	INT	NOT NULL,
	OrderNote	NVARCHAR(300),
	PRIMARY KEY	(OrderID,FoodID),
	CONSTRAINT	fk_ordered_order	FOREIGN KEY (OrderID)
				REFERENCES ORDER_FOOD(OrderID)
				ON DELETE CASCADE,
	CONSTRAINT	fk_ordered_food	FOREIGN KEY (FoodID)
				REFERENCES FOOD(FoodID)
				ON DELETE CASCADE,
	CONSTRAINT 	fk_cus_ordered	FOREIGN KEY (CustomerID) 
				REFERENCES USER_ACCOUNT(ID) 
				ON DELETE NO ACTION
)

GO

CREATE PROC Login
@userName NVARCHAR(20), @passWord NVARCHAR(20)
AS
BEGIN
	SELECT * FROM dbo.USER_ACCOUNT WHERE UserName = @userName AND Password = @passWord
END
GO



---MANAGER-

INSERT INTO USER_ACCOUNT VALUES ('admin', 'admin', N'anh', N'Nguyen', N'01-01-2001', N'Ha Tinh', N'0123', N'IMG', N'Manager');
